#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2021.1.0f1"
#define UNITY_VERSION_DIGITS "2021.1.0"
#define UNITY_VERSION_SUFFIX "f1"
#define UNITY_VERSION_VER 2021
#define UNITY_VERSION_MAJ 1
#define UNITY_VERSION_MIN 0
#define UNITY_IS_BETA 0
